# Generated by Django 2.1.7 on 2019-04-10 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data available')),
                ('end_date', models.DateField(verbose_name='Data end return')),
                ('price', models.FloatField(default=0.0)),
                ('pickupAdress', models.CharField(default='', max_length=1000)),
                ('returnAdress', models.CharField(default='', max_length=1000)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('tags', models.CharField(default='', max_length=1000)),
                ('image', models.CharField(default='', max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Profile', to_field='user_id')),
            ],
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Profile', to_field='user_id'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='original_Proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.LoanProposition'),
        ),
        migrations.AddField(
            model_name='loanproposition',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Profile', to_field='user_id'),
        ),
        migrations.AddField(
            model_name='loanproposition',
            name='stuff_for_lown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Stuff'),
        ),
    ]
